// =============================================================================
// mp-move — отправить отряд ПРОСТО В КЛЕТКУ, без цели и без боя.
//
// Автор: «добавь возможность отправлять отряды в пустоту так сказать, или в
// пустошь». В одиночной игре это было с самого начала (панель «Пустошь» ->
// «Отправить отряд», см. openLevy/arriveMarch в index.html), а в общий мир не
// переносилось: там у каждой отправки была конкретная цель — город
// (mp-attack), лагерь (mp-raid) или жила (mp-gather).
//
// Что отряд делает, дойдя: НИЧЕГО. Встаёт и ждёт приказа — mode "move"
// разбирает applyMarchArrive в mp-tick, переводя марш в state "hold". Это
// прямое указание автора: «отряд не принимает решения самостоятельно, только
// по клику». Дальше его можно перетащить пальцем на любую цель (mp-redirect
// сам подберёт задачу под то, что под пальцем) или отозвать домой
// (mp-recall).
//
// Единственная проверка сверх обычных — вода: высаживать отряд в море
// бессмысленно, одиночная игра это тоже не разрешает (см. openLevy). Маска
// воды — та же запечённая, что в mp-tick/mp-join.
//
// Тело запроса: { x:int, y:int, units:{inf:{1:n},...}, with_gen?:bool }
// Обвязка (клиент/бонусы/скорость марша/сохранение игрока) — самодостаточная
// копия из mp-gather, как и во всех остальных функциях этой папки: редактор
// в Dashboard относительных импортов не тянет.
// =============================================================================

import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

// Вставлено буквально из ../_shared/cors.js и ../_shared/rules.js — тот же
// приём самодостаточности, что и у остальных функций (см. их заголовки).
const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};
function jsonResponse(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...CORS_HEADERS, "Content-Type": "application/json" },
  });
}
function handleOptions(req) {
  if (req.method === "OPTIONS") return new Response("ok", { headers: CORS_HEADERS });
  return null;
}

// =============================================================================
// savePlayerState — запись состояния игрока с проверкой, что его никто не
// перезаписал, пока мы считали.
// =============================================================================
// Каждая функция здесь работает по схеме "прочитал строку игрока -> изменил
// объект state в памяти -> записал его ЦЕЛИКОМ обратно". Пока запросы к
// одному игроку идут строго по очереди, это верно. Но они идут не по
// очереди: клиент опрашивает mp-join каждые пять секунд (а тот пишет строку
// игрока — начисляет добычу), и тик мира (mp-tick) пишет её же, разрешая
// события. Если игрок нажал "Строить" в тот же миг, порядок получался
// такой:
//     действие  читает state (постройки нет, ресурсы целы)
//     mp-join   читает state (то же самое)
//     действие  пишет  state (ресурсы списаны, стройка в очереди)
//     mp-join   пишет  state — СВОЙ, прочитанный ДО действия
// и стройка вместе со списанием исчезала бесследно. Обратный порядок так же
// легко давал зеркальный исход — ресурсы списаны, а стройки нет. Ни ошибки,
// ни следа в логах: последняя запись просто затирала чужую.
//
// Лечится проверкой версии при записи. updated_at и так есть у строки и и
// так пишется при каждом изменении — используем его как метку версии:
// обновляем строку ТОЛЬКО если updated_at всё ещё тот, что мы прочитали.
// Не совпал — значит кто-то записал раньше нас, и наш объект state построен
// на устаревших данных; сообщаем об этом вызывающему, а не затираем.
// Отдельная колонка-счётчик не нужна: миграцию пришлось бы накатывать
// руками через дашборд (см. supabase/README.md), а updated_at уже на месте.
//
// Новая метка строго больше прочитанной (Math.max с +1 мс) — время на
// сервере может идти назад при коррекции часов, а метка версии обязана
// только расти, иначе устаревшее значение однажды совпало бы снова.
//
// Возвращает { ok:true } | { conflict:true } | { error }.
async function savePlayerState(admin, row, state) {
  const prev = row.updated_at;
  if (!prev) {
    // Строка прочитана без updated_at (старый вызывающий код) — сверять не с
    // чем; пишем как раньше, чтобы ничего не сломать, но и не притворяемся,
    // что проверили.
    const { error } = await admin.from("players")
      .update({ state, updated_at: new Date().toISOString() }).eq("id", row.id);
    return error ? { error } : { ok: true };
  }
  const nextIso = new Date(Math.max(Date.now(), Date.parse(prev) + 1)).toISOString();
  const { data, error } = await admin.from("players")
    .update({ state, updated_at: nextIso })
    .eq("id", row.id).eq("updated_at", prev).select("id,updated_at");
  if (error) return { error };
  if (!data || !data.length) return { conflict: true };
  // Своя же метка — на случай второй записи той же строки в этом запросе.
  row.updated_at = data[0].updated_at;
  return { ok: true };
}

// Ответ на проигранную гонку. 409 + retry:true — клиент (mpCall в
// index.html) повторяет такой запрос сам, молча: состояние он перечитает
// заново, так что повтор посчитается уже по свежим данным. Игрок ничего не
// замечает, а данные не теряются.
function conflictResponse() {
  return jsonResponse({ err: "Состояние изменилось, повторяю…", retry: true }, 409);
}

const TKEYS = ["inf", "arc", "cav", "sie"];
const emptyUnits = () => ({ inf: {}, arc: {}, cav: {}, sie: {} });
// Технический пол дорожного времени (секунды) — только чтобы t1 > t0 и
// событие прибытия не оказалось в прошлом на соседней клетке. К
// пятнадцатисекундной фазе боя отношения не имеет (см. одноимённую константу
// в mp-tick/mp-redirect — там тот же разбор).
const MIN_TRAVEL = 3;
const TIER_MULT = [1, 1.62, 2.55, 4.05, 6.20]; // index.html:2578
const TROOP_LOAD = { inf: 6, arc: 8, cav: 5, sie: 30 }; // index.html:2583-2587 (TROOP_TYPES[*].load)
const TROOP_SPEED = { inf: 1.00, arc: 1.10, cav: 1.70, sie: 0.60 };
const RACE_SPEED_MOD = { undead: { sie: 1.20 } };
const troopSpeedMod = (race, t) => (RACE_SPEED_MOD[race] && RACE_SPEED_MOD[race][t]) || 1;
// index.html:2725 troopMod(race,t,"load"). Раньше тут стояла ПУСТАЯ таблица с
// комментарием "сейчас ни у одной расы нет модификатора груза" — неверно:
// у нежити осадные всегда несли load:0.80. Это её честный размен: осадные
// нежити бьют вдвое сильнее (atk 2.20*1.05), но возят на 20% меньше. Без
// этой строки в общем мире нежить получала силу БЕЗ обратной стороны и
// собирала с точек на 25% больше, чем та же нежить в одиночке.
const RACE_LOAD_MOD = { undead: { sie: 0.80 } };
const troopLoadMod = (race, t) => (RACE_LOAD_MOD[race] && RACE_LOAD_MOD[race][t]) || 1;
const MARCH_SPEED_SCALE = 32;
const marchSlots = (hall) => (hall >= 22 ? 5 : hall >= 17 ? 4 : hall >= 11 ? 3 : hall >= 5 ? 2 : 1);
const RES = ["food", "wood", "stone", "gold"];
// amber:45 — index.html:2807. Точки Янтаря теперь реально сеются на общей
// карте (mp-join seedNodesAround / mp-tick applyNodeRespawn/applyAmbientSeed,
// AMBER_NODE_SHARE=0.12), так что этот ключ достижим — держим таблицу полной.
const GATHER_BASE_RATE = { food: 3000, wood: 3000, stone: 2250, gold: 1000, amber: 45 }; // index.html:2807

const epochOf = (hall) => (hall >= 25 ? 5 : hall >= 19 ? 4 : hall >= 13 ? 3 : hall >= 7 ? 2 : 1);
// bonuses(p) — тот же честный перенос, что и в mp-attack/_shared/rules.js
// (Фаза 6): нужны B.gather/B.gatherFW/B.gatherSG и B.march для скорости
// сбора/марша. ACADEMY_TREE — только узлы с этими тремя полями, без всего
// остального дерева (там их формулы идентичны полной копии в mp-attack).
const ACADEMY_GATHER_NODES = [
  { id: "eco_gfood1", field: "gatherFW", total: 0.15, max: 5 },
  { id: "eco_gwood1", field: "gatherFW", total: 0.15, max: 5 },
  { id: "eco_gstone1", field: "gatherSG", total: 0.15, max: 5 },
  { id: "eco_ggold1", field: "gatherSG", total: 0.15, max: 5 },
  { id: "eco_gfood2", field: "gatherFW", total: 0.35, max: 10 },
  { id: "eco_gwood2", field: "gatherFW", total: 0.35, max: 10 },
  { id: "eco_gstone2", field: "gatherSG", total: 0.35, max: 10 },
  { id: "eco_ggold2", field: "gatherSG", total: 0.35, max: 10 },
  { id: "eco_gall2", field: "gather", total: 0.25, max: 10 },
  // index.html:2218/2245 eco_amber0/eco_amber1 — своя ветка академии для
  // Янтаря, отдельная от gatherFW/gatherSG (см. isAmber-ветку ниже).
  { id: "eco_amber0", field: "gatherAmber", total: 0.05, max: 1 },
  { id: "eco_amber1", field: "gatherAmber", total: 0.35, max: 10 },
  { id: "eco_load1", field: "load", total: 0.15, max: 5 },
  { id: "eco_load2", field: "load", total: 0.25, max: 10 },
  { id: "mil_march1", field: "march", kind: "mult", total: 0.15, max: 5 },
  { id: "mil_march2", field: "march", kind: "mult", total: 0.15, max: 5 },
];
const GENERALS = {
  human: [{ apply: () => {} }, { apply: () => {} }], // ни один людской генерал не трогает march/gather
  dwarf: [{ apply: () => {} }, { apply: (b) => { b.march += 0.10; } }], // Гимрод
  elf: [{ apply: () => {} }, { apply: (b) => { b.march += 0.05; } }],   // Тариэль
  undead: [{ apply: () => {} }, { apply: () => {} }],
};
const RACES_MINUS = {
  human: { field: "prodGold", kind: "frac", value: -0.15 },
  dwarf: { field: "march", kind: "mult", value: 0.90 },
  elf: { field: "def", kind: "frac", value: -0.10 },
  undead: { field: "def", kind: "frac", value: -0.10 },
};
const RACE_EPOCHS_MARCH = {
  // Только строки, которые реально трогают march/gather (index.html:1767-1832)
  // — остальные поля той же таблицы (atk/def/prodX/...) здесь не нужны,
  // эта функция считает ТОЛЬКО B.march/B.gather*/B.load для нужд похода.
  human: [null, null, null, null, null],
  dwarf: [null, null, null, null, null],
  elf: [null, null, { field: "march", kind: "mult", value: 1.10 }, null, null],
  undead: [null, null, null, null, null],
};
const portalMarchBonus = (lv) => (lv <= 0 ? 0 : lv <= 10 ? lv * 0.005 : 10 * 0.005 + (lv - 10) * 0.01);

function bonuses(p) {
  const b = { march: 1, gather: 0, gatherFW: 0, gatherSG: 0, gatherAmber: 0, load: 0 };
  const mn = RACES_MINUS[p.race];
  if (mn.field === "march") { if (mn.kind === "mult") b.march *= mn.value; else b.march += mn.value; }
  const epoch = epochOf(p.b && p.b.hall), track = RACE_EPOCHS_MARCH[p.race];
  for (let i = 0; i < epoch; i++) {
    const e = track[i]; if (!e) continue;
    if (e.kind === "mult") b[e.field] *= e.value; else b[e.field] = (b[e.field] || 0) + (e.value || 0);
  }
  (GENERALS[p.race][(p.gen && p.gen.id) || 0]).apply(b);
  b.march *= 1 + portalMarchBonus((p.b && p.b.portal) || 0);
  // index.html:3760-3767/3780-3787 TALENTS (g1-g5) и GENERAL_TREE (gt_a7/
  // gt_a8) — только те узлы, что реально трогают march/gather/load, тот же
  // принцип сужения, что и у ACADEMY_GATHER_NODES выше. Фаза 10, кусочек 3:
  // p.gen.tal теперь реально заполняется (mp-talent, кусочек 2).
  const T = (p.gen && p.gen.tal) || {};
  const g = (id) => T[id] || 0;
  b.load += g("g1") * .04; b.gather += g("g2") * .04; b.march *= 1 + g("g3") * .03;
  b.gatherFW += g("g4") * .05; b.gatherSG += g("g5") * .05;
  const tech = p.tech || {};
  const multAcc = {};
  ACADEMY_GATHER_NODES.forEach((n) => {
    const lv = tech[n.id] || 0; if (!lv) return;
    const inc = n.total * (lv / n.max);
    if (n.kind === "mult") multAcc[n.field] = (multAcc[n.field] || 0) + inc;
    else b[n.field] = (b[n.field] || 0) + inc;
  });
  Object.keys(multAcc).forEach((f) => { b[f] = (b[f] === undefined ? 1 : b[f]) * (1 + multAcc[f]); });
  b.load += g("gt_a8") * .03; b.march *= 1 + g("gt_a7") * .03;
  return b;
}

function marchSpeed(units, race, marchBonus = 1) {
  let s = 99;
  TKEYS.forEach((t) => {
    for (let i = 1; i <= 5; i++) {
      if ((units[t] && units[t][i]) > 0) s = Math.min(s, TROOP_SPEED[t] * troopSpeedMod(race, t));
    }
  });
  if (s > 90) s = 1;
  return s * MARCH_SPEED_SCALE * marchBonus;
}


// ---- Рельеф (дословная копия из mp-join/index.js, самодостаточная — см.
// пояснение о Dashboard-редакторе выше) — раньше здесь этого блока не было
// вовсе: respawnOffset/applyAmbientSeed ниже сеяли точки/лагеря совсем
// вслепую (комментарий на этом месте раньше честно предупреждал: "тоже не
// проверяет воду"). Автор явно попросил, чтобы точки ресурсов не появлялись
// ни на неровных поверхностях, ни друг в друге, ни в реках — держать это
// только на клиенте/в mp-join было половинчато: respawn истощённой точки и
// фоновый ambient-подсев работают именно отсюда, mp-tick.
function hash2(x, y, s) { let h = x * 374761393 + y * 668265263 + s * 1274126177;
  h = Math.imul(h ^ (h >>> 13), 1274126177); return ((h ^ (h >>> 16)) >>> 0) / 4294967296; }
function noise(x, y, s) {
  const xi = Math.floor(x), yi = Math.floor(y), xf = x - xi, yf = y - yi;
  const u = xf * xf * (3 - 2 * xf), v = yf * yf * (3 - 2 * yf);
  const a = hash2(xi, yi, s), b = hash2(xi + 1, yi, s), c = hash2(xi, yi + 1, s), d = hash2(xi + 1, yi + 1, s);
  return (a * (1 - u) + b * u) * (1 - v) + (c * (1 - u) + d * u) * v;
}
function ridge(x, y, s) { return 1 - Math.abs(2 * noise(x, y, s) - 1); }
const RW_SEED = 12345, RW_SEA = 0.235;
function rwSstep(a, b, x) { const t = Math.min(1, Math.max(0, (x - a) / (b - a))); return t * t * (3 - 2 * t); }
function rwRegionKind(x, y) {
  return { mount: rwSstep(0.40, 0.72, noise(x / 40, y / 40, RW_SEED + 55)),
           plat: rwSstep(0.62, 0.84, noise(x / 34, y / 34, RW_SEED + 88)),
           rough: noise(x / 26, y / 26, RW_SEED + 123) };
}
function rwHeightRaw(x, y) {
  const wx = (noise(x / 34, y / 34, RW_SEED + 101) * 2 - 1) * 13;
  const wy = (noise(x / 34, y / 34, RW_SEED + 102) * 2 - 1) * 13;
  const X = x + wx, Y = y + wy;
  const R = rwRegionKind(x, y);
  const cont = noise(X / 62, Y / 62, RW_SEED + 201);
  let e = 0.16 + cont * 0.50;
  const amp = 0.16 + 0.84 * R.mount + 0.35 * R.rough;
  e += (noise(X / 27, Y / 27, RW_SEED) * 0.20 + noise(X / 13, Y / 13, RW_SEED + 9) * 0.10
    + noise(X / 6, Y / 6, RW_SEED + 21) * 0.045) * amp;
  e += ridge(X / 17, Y / 17, RW_SEED + 37) * 0.33 * R.mount;
  e += R.mount * 0.10 - (1 - R.mount) * 0.05;
  if (R.plat > 0.02) {
    const terr = Math.round(e * 6.0) / 6.0;
    e = e * (1 - R.plat * 0.80) + terr * (R.plat * 0.80);
  }
  if (e >= 0.42) {
    const k = rwSstep(0.42, 0.68, e);
    e += (noise(x / 2.4, y / 2.4, RW_SEED + 180) - 0.5) * 0.075 * k
      + (noise(x / 5.5, y / 5.5, RW_SEED + 181) - 0.5) * 0.055 * k;
  }
  return Math.max(0.02, Math.min(1, e));
}
function rwHeightAt(x, y) {
  const c = rwHeightRaw(x, y);
  const s = (rwHeightRaw(x + 0.7, y) + rwHeightRaw(x - 0.7, y) + rwHeightRaw(x, y + 0.7) + rwHeightRaw(x, y - 0.7)) * 0.25;
  return c * 0.55 + s * 0.45;
}
// ---- НАСТОЯЩАЯ карта воды (запечена из heightmap/elevation-v6.bin) --------
// Процедурная формула rwHeightAt выше — НЕ та вода, которую видит игрок.
// Замер по всей карте: она не видит 96% настоящей воды, то есть сервер
// спокойно ставил точки и лагеря прямо в реки, а 3D-движок рисует настоящий
// рельеф — отсюда рудники и каменоломни на берегу и в русле.
//
// Сам elevation-v6.bin — 5.76 МБ, в функцию его не зашить и качать в рантайме
// незачем. Здесь лежит его сжатая битовая маска (worldgen/bake_water_mask.mjs):
// 1 бит на блок WATER_MASK_STEP x WATER_MASK_STEP клеток, блок считается водой,
// если мокра ЛЮБАЯ его клетка — консервативно, лучше лишний запас у берега,
// чем точка в реке. Проверено: пропущенной воды 0.0% против 96.2% у формулы,
// ценой 3.1% карты в виде запаса вдоль берегов.
// Перепечь после смены heightmap: node worldgen/bake_water_mask.mjs
const WATER_MASK_STEP = 4, WATER_MASK_W = 600, WATER_MASK_H = 300;
const WATER_MASK_HALF_X = 1200, WATER_MASK_HALF_Z = 600; // мировые полуразмеры запечённой области
const WATER_MASK_B64 = "///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////n//////////////////////////////////////////////////////////////////////////////////////////////////8HIPD///////////////////////////////////////////////////////////////////////////////////////////////8AAPD////w/z/g//8///////////////////////////////////////////////////////////////////////9/OOD/////fw8AAGDf/3+A9w0AGgAP3P////j///////////////////////////////////////////////////////////////8BAAD/////fwAAAICBjzMAAAAAAAACAP7/AwD+/////////////3/w//////////////////////////////8//////////////wcAAADw//8/PgAAAACADwAAAAAAAAAAADgAAADA/////////////x/A////////////z/////////////////9/9v///////3PgPwAAAADA/5EfdgAAAAAAAAAAAAAAAAAAAAAAAAAAwP//h////////wMA/v//////////h/////////////////9jDsD//////wAAAAAAAAAAgAAA4AEAAAAAAAAAAAAAAAAAAAAAAAAAAOD/APz///8HDgAA/P//////////A////////x/g/////z/gDQD+////DwAAAAAAAAAAAAAAwAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAeAOD/fz8AGAAA/P//////////AP7//////4HAP/D//w+AHQD4////AwAAAAAAAAAAAAAAgAEAAAAAAAAAAAAAAAAAAAAAAAAAAAB8AAAAAAAAGAAA/P//////f/g/APj/////P4CAD+D//wOAPh/g//9/AAwAAAAAAAAAAAAAgAMAAAAAAAAAAAAAAAAAAAAAAAAAAEBgAAAAAABAMAQQ/P//////f4ABAADw////DwAAAOD//wEA9P8D/z8AAAAAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAABggAEAAABABjAQ/v//////fwAAAAAA+P//AQAAAMD//wcA/OEP/AHAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAABggAEAAAAACBAA/v//////fwAAAAAAAAAAAAAAAID/AQ8A+Ad/AADgAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAEAAACDAA////////fwAAAAAAAAAAAAAAAAAOABwA6C74AABAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAcAAAAHOA////////fwAAAAAAAAAAAAAAAAAAABgAACjgwADAGAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAA4AEAAM+H////////fwwAAAAAAAAAAAAAAA4AAHgAAAD4//8AHwAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAwAEADA7A////////fxwAAAAAAAAAAAAAAAAAAPADAABg//8BDwAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAAAAgAUAAADw////////fwgAAAAAAAAAAAAAAAAAAMAHAAAAAP4PAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAQAAAAQAAADg////////PzAAAAAAAAAAAAAAAAAAAAAPAAAAAAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACABwAAAAAAAADg////////HzgAAAAAAAAAAAAAAAAAAAB8AAAAAAD8PAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwAAAAgAAADw////////DwwAAAAAAAAAAAAAAAAAAAB4AAAAAAD8/zcAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAAAAAAADw////////BwAAAAAAAAAAAAAAAAAAAADgAAAAAAD8738AAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAGAAAQDw////////AwAAAAAAAAAAAAAAAAAAAADgAAAAAACAQP0PAAAgAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAA4AFMAGADA8D5////////AQsAAAAAAAAAAAAAAAAAAABnAAAAAAAAAMAfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwA/MAAAAAID5////////AR8AAAAAAAAAAAAAAAAAAABjAAAAAAAAAAB4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8MAAAAAAD4////////AB8AAAAAAAAAAAAAAAAAAABgAAAAAAAAAAB4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPQDAAAAAQD4////////AB8AAAAAAAAAAAAAAAAAAADgAQAAAAAAAADwAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA/AAAAAAD8////////AD8AAAAAAAAAAAAAAAAAAADAAwAAAAAAAADgAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAH+AAAwAAD8//////9/ADwAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAACAgwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAwDAAAD8////////ABgAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAADAzwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACADwCAAAD+////////AAwAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAADg/gEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgAABgD+//////9/AAAAAAAAAAAAAAAAAAAABgMABwAAAAAAAABw+B8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAABgD+//////9/BwAAAAAAAAAAAAAAAACAAAAADgAAAAAAAADw4P8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIeBAADAD+////////AyAAAAAAAAAAAAAAAACAAAAAHgAAAAAAAADwMPwBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACI4P8DDAD+////////AQAAAAAAAAAADAAAAAAAAAAA+AAAAAAAAADwAIADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgf8HBAD+////////AQAAAAAAAAAABAAAAAAAAAAA8AEAAAAAAAA+AAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAQAOBAD8////////AAEAAAAAAAAAAAAAAAAAAAAAwAMAQAAAAAAPAMAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOABAAAAAAAAAQA8AAD8////////gAEgAAAAAAAAAAAAAAAAAAAAAAMAwAAAAIAPAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAPAAAAAGAAAAB4GADw////////OAFwAAAAAAAAAAAAAAAAAAAAAAcAAAAAAIAHAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+Hx8AAGAAAwDgAQDw////////PAAwAAAAAAAAAAAAAAAAAAAAAA4AAAAAAMADAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw/38AAMA5AgDAAwDg////////PAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAMABAIADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACA8fEDAMAZADMABwDA////////OAAAAAAAAAAAAAAAgCEAAAAAAAwAAAAAAMABAMABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAPAAA4AAMADgDA////////AAAAAAAAAAAAAAAAgCAAAAAAABgAAAAAAMABAMAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+AABwAAAADADA////////AQAAAAAAAAAAAAAAAAAAAAAAADgAAAAAAMAAAMAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AwDgAQAAPAAA////////AQAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAMABAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAHwCAAQAA+AAA/v//////AQAAAAAAAAAAABgAAAAAAAAAADgAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgCABwAAwAAA/v//////AwAAAAAAAAAAAAwAAAAAAwAAADgAAAAAOMABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+AAAHwAAwAAA/v//////AwAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAMABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AMAPAAAwAEA/P//////w2MAAAAAAAAAAAAAAAAAAAAAAhgAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AMAAAwAEA+P//////xw8AAAAAAAAAAAAAAAAAAAAAAAAAAACAAMABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAgAcA+P//////hw8AAAAAAAAAAAAAAAIAAAAAAAAAAACAAYADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAAAAAAB8A+P//////BwgDAAAAAAAAAAAAAAIAAAAAAAAAAAAAAIADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAAAAADwA8P//////DwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4AAAAAAAAAOAPAAAAADgA8P//////DwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8AQAAAAAAAID/AAAAABwA8P//////DwAAAAAAAAAAADgAAAAAAAAAAAAAAAAAAHgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADPAwAAAAAAAAD4HwAAAHgA+P//////DwAAAAAAAAAAADwAAAQAAAAAAAAAAAAAAFwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAHBwAAAAAAAAAAfwAAAOAA+P//////HwAAAAAAAAAAAA5ADAQAAAAAABAAAAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPABDgAAAAAAAAAA4AEAAMAB+P//////HwAAAAAAAACAAAZADAAAAAAAABgAAAAQAHwAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAHEAAAAAAAAAAwIcBAMAB+P//////HwAAAAAAAACAAQwIAAAAAAAAABAAAAAAADwAAP8HAAAAAAAAAAAAAAAAAAAAAAAAAAAAcBwAPEAAAAAAAAAAAJ8ZAIAH/P//////PwAAAAAAAACAAA4YAAAAAAAAAAAAAAAAADwAwM8PAAAAAAAAAAAAAAAAAAAAAAAAAAAA8A8AMAAAAAAAAAAAADwIAAAP////////PwAAIAAAAAAAwA8AAAAAAAAAAAAAAAAAADwA+AEMAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AMAcAAAAAAAAAAAAPAAAAAO////////fwAA/AAAAAAAwAMAAAAAAAAAAAAAAAAAADwAfgAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAOABAACM////////fwAAfgAAAAAC4AEAAAAAAAAAAAAAAAAAAB4ADwAeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAIAHAAD8/////////4APBgAAAAD/fwAA+AAAAAAAAAAAAAAAAAwABwAOAAAAAAAAAADgAwAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAOAAD8/////////+PfBwAAAPj/PwAAPwAAAAAAAAAAAAAAABzwBwDuAQAAAAAAAADwDxwAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAcAADw///////////+BwAAwP+ZHQCADwAAAAAAAAAAAAAAADz+AwD8ewAAAAAAAAA4/v//AAAAAAAAAAAAAAAAwAMAAAAAAAAAAAD4AADw////////fz5+AAAA+N8DAADAAQAAAAAAAAAAAAAAABweAAA4/wAAAAAAAAAc+PP/AQAAAAAAAAAAAAAAgAMAAAAAAAAAAADwAADw//////8PfgQAAAAAPx0AAAD8AAAAAAAAAAAAAAAAABgHAAAAzgEAAAAAAAAOAACAAAAAAAAAAAAAAAAAAD8AAAAAAAAAAADgAQDw//////8DAAAAMADAF/z4/9Y/AAAAAAAAAAAAAAAAANgDAAAAgAcAAAAAAIAHAAAAAAAAAAAAAAAAAAAAAD4AAAAAAAAAAACABwDw//////8BAAAAAADwA/j///8DAAAAgAEAAAAAAAAAAPgDAAAAAA8AAAAAAMABAAAAAAAAAAAAAAAAAAAAAPACAAAAAAAAAAAAHgDw//////8BAAAAAO5wAMAPwP8AAAAAgAEAAAAAAAAAAPABAAAAAAwAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAPAHAAAAAAAAAAAAPADw//////8BAAAAgP84AAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAIAPAAAAAAAAAAAAMADw//////8BAAADwPs/EAAAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAJgAAAAAAHwAAAAAAAAAAAAAAAAAAAAAAAAeAAAAAAAAAAAA4ADw//////8BAAAK4IEfGAAAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAPABAAAAAB4AAAIAAAAAAAAAAAAAAAAAAAAcAAAAAAAAAAAAwAHw//////8BAACI/wAHCAAAAAAAAAAAAAAAAADgAQAAAAAAAAAAAOAPAAAU4P8AAAAAAAAAAAAAAAAAAAAAAAB8AAAAAAAAAAAAgAPw//////8BAACA/wAAAAAAwAMAAAAAAAAAAADgAwAAAAAAAAAAAAA/ALD//v8DAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAAAAAAfw//////8BAADALwAAAAAAwAEAAAAAAAAAAADAAwAAAAAAAAAAAAA+AP7/P8ADAACAAQAA8AEAAAAAAAAAAADAAQAAAAAAAAAAAAbw//////8BAADgAQAAAAAAAAAAAAAAAAAAAAAAAwAAAEAAAAAAAABw4P+BBwAHAACAAQAA+AMAAAAAAAAAAADADwAAAAAAAAAAAAbw//////8BAAD4AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADg+wEAAAAHAAABAAAAAAAAAAAAAAAAAAAA/gAAAAAAAAAAAAbw//////8BAAC8AAAAAMABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAPwAAAAAGAIABAAAAAAAAAAAAAAAAAAAA8AMAAAAAAAAAAA7w//////8BAAAYAAAAALYBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgAAAAAHAAAAAAAAAAAAAAAAAAAAAAAA4AcAAAAAAAAAAAzg//////8BAAAcAAAAjPkBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAzg//////8B4AAOAAAA+PiBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAHwAAAAAAAAAAAzA//////8B4AAHAAAA8ACAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAB+AAAAAAAAAAAAAAAAAAAAAAAAAHgAAAAAAAAAAAzA//////8B4AAHAAAI8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAD+AQAAAAAAAAAAAAAAAAAAAAAAAOABAAAAAAAAADyA//////8Q8PgDAAAA+P8AAjj3AwAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAACYAwAAAAAAAAAAAAAAAAAAAAAAAMABAAAAAAAAAPgA//////8Q/v8BAAAAnv8Pgv//fwAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAADwAAAAAAAAAAAAAAAAAAAAAAAMABAAAAAAAAAMAB/v////8An38AQAAAD4APoP///38AAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAfgAAAAAAAAAAAAAAAAAAAAAAAOABAAAAAAAAAIAf/v////8AAwAA8ACnAwD+/wEA/P//BwAAAAAAAAAAAAAAAAAAAAAAGAAAAAAA+AAAAAAAAAAAAAAAAAAAAAAAAOD/AAAAAAAAIAB//P////8AAwAA+Lf/AQD8fwAAAPD/HwAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AQAAAAAAIAD4/P////+BBwaAv9/5AAAADAAAAAA4PAAAAAAAAAAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwBwACAAAAAADA+/////+B/w/gH/wBAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAACABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACADwAAAAAAAACA/////////x/wAHAAIAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAADAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAHwAAAAAAAAAA/v//////F/g+AAAAIAAAAAAAAAAAwAEAAAAAAAAAAAAAAAAAAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgAAAAAAAAAA/P//////D/A/BgAAAAAAAAAAAAAAgAEAAAAAAAAAAAAAAAAAAAB8ABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAAAAAAAAA+P//////D4ABBgAAAAAAAAAAAAAAwAEAAAAAAAAAAAAAAAAAAAAeADAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAPwAAAAAAAAAA+P//////BwAAAIAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAHBDAAgAAAAAAAAAAAgP8H4B8AAAAAAAAAAAAATwAAAAAAAAAA+P//////DwAAAPABAAMAAAAAAAAAwAIAAAAAAAAAAAAAAAAAAAADBgAAwAAAAAAAAAAAwP8P/v8BAAAAAAAAAAAA/AAAAAAAAAQA+P//////HwAAAPAAAAEQAAAAAAAAwAcAAAAAAAAAAAAAAAAAAIADAAIA2AAAAAAAAAAA8AD8P/A/AAAAAAAAAAAA+AEAAAAAAGwH+P//////PwAAwPAAAAAYAAAAAAAAgD8AAAAAAAAAAAAAAAAAAIADAAMCCAAAgAEAAAAAfADwEQD/AQAAAAAAAAAA8AH4OAAAAGAG+P//////PwAA8DEAAAAAAAAAAAAAAPw7AAAAAAAAAAAAAAAAAMADgADeAAAAgAEAAAAAHwBAAADgBwAAAAAAAAAA4IH//wEAAAAA+P//////PwAA8AMCAAAAAAAAAAAAAOQ/AAAAAAAAAAAAAAAAAIADAACYAAAAgAEAAACAAwAAAAAADwAAAAAAAAAAcMCf/wMAAAAA+P//////PwAA4AMaABgAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAMADAAAYAAAAiAEAAADAAQAAAAAADAAAAAAAAAAAcOABAA8AAAAA/P//////fwAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMABAAAMAAAADAAAAADgAAAAAAAAAAAAAAAAAAAA4HAAAB4ABgAA/P///////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMABAAAMAAAADAAAAAAwAAAAAAAAAAAAAAAAAAAAgD8AADgAAAAA/v//////3wAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIABAAAYAAAAAAAAAAA8AAAAAAAAAAAAAAAAAAAAAD8AADAAAAAA/v//////3zkAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAMAAAAAQAAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAA////////nz8AAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIMAAAAAAAAAAAAAAAAAfAAAAAAAAAAAAAAAAAAAAAAAAAOABAACA////////Dx8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYOAAAADwAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAMAHAACA////////DwQAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAA4PAAAADwAwAAAAAAAIADAAAAAAAAAAAAAAAAAAAAAAAAAIA/AOCA////////DwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwH0AAAAAAwAAAAAAAMABAAAAAAAAAAAAAAAAAAAAAAAAAAB4AODA////////BwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAAAAAAMABAAAAAAAAAAAAAAAAAAAAAAAAAADgATDA////////BwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAOAAAAAAAAAAAEAAAAAAAAAAAAAAAADABxDA////////BwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgA8AAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHxDG////////DwAAAAAAAAAAAAAAAAAAAAAADwAAAAAAAAAAAAD4/wMAAAAAAAAAAAAAAHgAAAAAAAAAAAAAAADAAAAAAAAAAAAA/ADG////////DwAAAAAAAAAAAAAAAAAAAAAADwAAAAAAAAAAAAD8/wAAAAAAAAAAAAAAABwAAAAAAAAAAAAAAABAAAAAAAAAAAAA4AHA////////DwAAAAAAAAAA4AEAAAAAAAAADAAAAAAAAAAAAIBPAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAOA////////3wAAAAAAAAAA8AcAAAAAAAAACAAgAAAAAAAAAPAHAAAAAA4AAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcA/////////x8AAAAAAAD4Px8AAAAAAAAAGAAAAAAAAAAA8H8AAAAAAA4AAAAAAAABAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYA/////////38AAAAAAAD+HzwAAAAAAAAACAAAAAAAAAA48B8AAAAAAAAAAAAAAAADAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4A////////D+ADAAAAAPAfAHAAAAAAAAAAAAAAAAAAALAfAAAAAAAAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwA////////B+A/MAAAAPwDAHAAAAAAAAAAAAAAAAAAAPwHAAAAAAAAAAAAAAAAAAAMgAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgA/v//////BwB8cB4AAG4AAGAAAAAAAAAAAAAAAAAAABwAAAAAAAAAAAAAAAAAAAAcwAMAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAOAD/P//////BwBo/T9w/AcAAOAAgAMAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAY8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAP/P//////BwDg33P4/wMAwMABzwEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAe/v//////BwDAD+DfnwAAgMDf/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4////////BwCAA8CPAwAAAID/cwAAAAAAAAAAADgAAAAAAAAACAAAAAAAAAAAAADgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw////////AwAIBwAAAAAAAADgAAAAAAAAAACA338AAAAAAAAAGAAAAAAAAAAAAADAHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACA////////HwAMDgAAAAAAAAAAAAAAAAAAAADA/y8AAAAAAAAAGAAAAIAB+H8AAAAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v//////AwAEnB8AAAAAAAAAAAAAAAAAAADwYA4AAAAAAAAAGAAAAAAAfB4AAAEABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v//////QwAAeD8AAAAAAAAAAAAAAAAAAAAAAAcAAAAAAHAAGAAAAAAADgAAAAEAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/P//////wwAA8PMLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPABAAAAAAAABwAAAACAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v//////AwAA4OEfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAACAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////BwAA4IA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAADAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////BwAAwABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAgAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v//////DwAAwADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/P//////DwAAwADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB+AAA4AAAAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/P//////DwAAwAHACQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPD/AwAwAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+P//////HwAAwAGAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7DBwAAAAAAAAAeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8P//////HwAAgAMAPwEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwH8ABgAAAAAAAAAPAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8P//////HwAAAAMA8H8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AMADgAAAAAAAMADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8P//////DwCAgQMA4P8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAeAAAHAAAAAAAAOwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4P//////BwCA8QEAAMADAAAAAAAAAAAAAAAAAAAAAAAAAID/DwAAGAAAAAAAAHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8P//////AwCA+AAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAPD/DwAAOAAAAAAAAD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8P//////AAAAOAAAAAAWAAAAAAAAAAAAAAAAAAAAAAAAAPjCAAAAcAAAAAAAsAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/P////9/AAAAMAAAAAA+AAAAAAAAAAAAAAAAAAAAAAAAAD4AAAAA4ABwjAAA/wMAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAA/v////8/AAAAAAAAAAD8AAAAAAAAAAAAAAAAAAAAAAAAwA8AACAAwAP8/gfA7wAAAAAA4AAAAAAAAAcAAAAAAAAAAAAAAAAAAAAA/v////8fAAAAAAAAAADgAQAAAAAAAAAAAAAAAAAAAAAAwAMAACAAgMfe/x/8AQAAAAAAYAAAAAAAgAMAAAAAAAAAAAAAAAAAAAAA/v////8fAAAAAAAAAAAAfwAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAOfHh/9/AAAAAAAAAAAAAAAAAAAAAAAgAAEAAAAAAQAAAAAA/v////8fAAAAAAAAAAAA/wAAAAAAAAAAAAAAAAAAAAAA8AAAAAAAAPbHB/F/AAAAAAAAAAAAAAAAAAAAAAAwgAMAAAAAAQAAAAAA//////8fAAAAAAAAAAAAxgEAAAAAAAAAAAAAAAAAAAAAcAAAAAAAgP/DA+AEAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAHAAAAAA//////8/AAAAAAAAAAAQgAMAAAAAAAAAAAAAAAAAAAAAYAAAAAAA4B8AAAAAAAAAAAAAfAAAAAAAAAAAAAAAAAAAAAAAAPABAAAA/v////9/AwAAAAAAANwBAAcAAAAAAAAAAAAAAAAAAAALeAAAAAAA/AAAAAAAAAAAAAAAfAAAAAAAAAAAAAAAAAAAAAAAAMAHAAAA/P//////AgAAAAAAANwBAA4AAAAAAAAAAAAAAAAAAOB/fwAAAADwHwAAAAAAAAD+/wAACAAAAAAAAAAAAAAAAAAAAAAAAAAfAAAA/P//////AQAAAAAAAAAAABwAAAAAAAAAAAAAAAAAgPj/LwAAAAD9AwAAAAAAAPj//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAA/P//////AwAAAAAAAgAAAHgAAAAAAAAAAAAAgAEA4D/AAAAAAIA/AAAAAAAAAP4HAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAA/P//////BwAAAAAAAwAAAOAAAAAAAAAAAAAAAAMA/g8AAAAAAPwHAAAAAAAAgG8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAAAA/P//////BwAAAAAAAQAAAOAAAAAAAAAAAAAAAAMAPAIAAAAAgH8AAAAAAAAA8AEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAQAA/v//////BwAAAAAAAAAAAMAHAAAAAAAAAAAAAAAAAAAAAAAAwAcAAAAAAADg/wAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAACAAQAA/P//////BwAAAAAAAHAAAIAPAAAAAAAAAAAAAAAAMAAAAAAAwAMAAAAAAADwHwAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAACAAwAA+P//////BwAAAwAAAGAAAAAGAAAAAAAAAAAAAAAAcAAAAAAAgAcAAAAAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAgA8ABwAA+P//////BwAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAeAAAAAAAAA4AAAAAAOAfAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAwAcADgAA+P//////BwAAAAAAAAAAAADeyAAAAAAAAAAAAAAAUAAAAAAAAA4AAAAAAP4DAAAAAAAAAEBgAAAAAAAAAAAADAAAAAAAAAEADAAA/P//////BwAAAAAAAAAAAAD8/wcAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAD8AAAAAAAAAAMAAAAAAAAAAAAAADAAAAAAAAAAAHACA/P//////BwAAAAAAAAAAAACw/w/8wQEAAAAAAAAAAAAAAAAAgA8AAAAAgAMAAAAAAAAAIABwAAAAAAAAAAAADAAAAAAAAAAAOACA////////B0AIAAAAAADAAAAAAHz+/wMAAAAAAAAAAAAAAAAAwAcAAAAAwAEAAAAAAAAAIAD+AAAAAAAAAAAADAAAAAAAAAAA8AGA////////B8A4AAAAAADAAQAAAPgHfwcAAAAAAAAAAAAAAAAA4AAAAAAA4AAAAAAAAAAAAIAfAAAAAAAAAAAAHAAAAAAAAAAA4H8A////////BwAYAAAAAADAAAAAAOADMAYAAAAAAAAAAAAAAAAA4AAAAAAAcAAAAAAAAAAAAOADAAADAAAAAAAAGAAAAAAAAAAAAP7/////////E4EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAMAAAAAAAAACA9/8AAAADAAAAAAAAGAAAAAAAAAAAAMD/////////M4MABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAMAAIADPQAAAAAAIODh/z8AAAAAAAAAAAAAOAAAAAAAAAAAAACA////////AwEADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAMAAP//HwAAAAAA/v93HQAAAAAAAAAAAAAAMAAAAAAAAAAAAAAA////////AwAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgQMAgP/8BwAAAID+/78/AAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAA////////BwAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAEA4AEAAAAAAPj/AQAcAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAA////////BwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAEAcAAAAAAAAPwDAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAA/v//////DwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwCAAOAAAAAAAAA8AAAAAAAAAAAAAQAAAAAAAwAAAAAAAAAAAAAAA/v//////DwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4PwBHAAAAAAA/gMAAAAAAAAAAAAA4AEAAAAAwAEAAAAAAAAAAAAA/v//////H2cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4P8/PwAAAADA/wAAAAAAAAAAAAAA4AAAAAAAgAEAAAAAAAAAAAAA/v////////8ChgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4Af/fwAAAADwAwAAAAAAAAAAAAAAAAAAAAAAwAEAAAAAAAAAAAAA/v////////8fgAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8ADg4QMAAAA4AAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAA/P//////H/j/AwYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeAAAwA8AAAA+AAAAAAAAAAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAA+P//////H8D8HwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPwAAAD4AAMB/AAAAAAAAAAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAA+P//////H4APvwEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAHwAAAHgAwPsDAAAAAAAAAAAAAAAAAAAAAAAAMAMAAAAAAAAAAAAA8P//////HwAA/icAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAQAAAOAA8H8AAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAA/P//////HwAA/P/nP/D4EQAAAAAAAAAAAAAAAAAAAAAAAADgAQAAAMADfgcAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAA+P//////HwAAAPr//P//fwAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAICPHwMAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAA+P//////HwAAAAI/4L9vfwAAAAAAAAAAAAAAAAAAAAAAAADwAAAAAAD+hwMAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAA+P//////HwAAAAAIQAQA6AAAAAAAAAAAAAAAAAAAAAAAAADwAAAAAAD4wAEAAAAAAABwAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAA+P//////PwAAAAAAAAAAwAEAAAAAAAAAAAAAAAAAAAAAAAB4AAAAAAAA4AAAAAAAAAB4AAAAAAAAAABwAAAADAAAAAAAAAAAAAAA/P//////PwAAAAAAAAAAgAMAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAD8AAAADgAAAAAAAAAAAAAA////////fwAAAAAAAAAAgAcAAAAAAAAAAAAAAAAAAAAAAOAfAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAD/AQAADAAAAAAAAAAAAAAA/////////yAAAAAAAAAAAD4AAAAAAAAAAAAAAAAAAAAAAPgPAAAAAAAAMAAAAAAAAAAAAAAAAAAAwPCHAQAADAAAAAAAAAAAAAAA/////////yEAAAAAAAAAAP4AAAAAAAAAAAAAAAAAAAAAAPwAAAAAAAAAGAAAAAAAAAAAAAAAAAAA8P+BAQAADgAAAAAAAAAAAACA/////////wMAAAAAAAAAAPwDEAB4AAAAAAAAAAAAAAAAAM8AAAAAAAAAGAAAAAAAAAAAAAAAAAAA9z/AAQAADAAAAAAAAAAAAAAA/////////wcAAAAAAAAAAMD///3/AAAAAAAAAAAAAAAAmMMBAAAAAAAAGAAAAAAAAAAAAAAAAADwbwDgAAAAHAAAAAAAAAAAAAAA/////////wcAAAAAAAAAAAD////vAAAAAAAAAAAAAAAA/IMBAAAAAACAHwAAAAAAAAAAAAAAAAD4bwDwAAAAGAAAAAAAAAAAAACA/////////wcAAAAAAAAAAAA+gD/gAAAAAAAAAAAAAAAA/gAAAwAAAADADwAAAAAAAAAAAAAAAAA8fABwAAAAMAAAAAAAAAAAAADA/////////wcAAAAAAAAAAAAAAADADwAAAAAAAAAAAAAABwCCAwAAAADAAAAAAAAAAAAAAAAAAAAPuABwAAAAMAAAAAAAAAAAAAAA/////////wMAAAAAAAAAAAAAAACAHwAAAAAAAAAAAABgBwDiAAADAABgAAAAAAAAAAAAAAAAAAAHgAAwAAAAMAAAAAAAAAAAAACA/////////wMAAAAAAAAAAAAAAAAAPGA4AAAAAAAAAAD/AwAAAAADAABgAAAAAAAAAAAAAAAAAIADAAAwAAAAMAAAAAAAAAAAAACA/////////wMAAAAAAAAAAAAAAAAA8P//AGAAAAAAAOD/AQAAADwAAABwAAAAAAAAAAAAAAAAAIABAAAwAAAAMAAAAAAAAAAAAADg/////////wcAAAAAAAAAAAAAAAAA4P/v/8AHAAAAAPyIAAAAAAwAAAA6AAAAAAAAAAAAAAAAAMAAAACwAAAAMAAAAAAAAAAAAADw/////////wYAAAAAAAAAAAAAAAAAAP+n/+MPAAAAgD8IAAAAAAAAAAAfAAAAAAAAAAAAAAAAAPAAAACwAQAAMAAAAAAAAAAAAAD4/////////wAAAAAAAAAAAAAAAAAAAOQAeP/8BwAAwA8AAAAAAAAAAAAfAAAAAAAAAAAAAAAAAHgAAABwAADgGAAAAAAAAAAAAAD4////////fwAAAAAAAAAAAAAAAAAAAAAAAD/4DwAA4AcAAIABAAAAAAA/AAAAAAAAAAAAAAAAABwAAABwAADgHAAAMAAAAAAAAADw////////PwAAAAAAAAAAAAAAAAAAAAAAAACAfQAAfAAAAIABAAAAAAA4AAAAAAAAAAAAAAAAABwAAABwAAAIDiAAOAAAAAAAAADw////////DwAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAfwAAAAAAAAAAAAA8AAAAAAAAAAAAAAAAABwAAADwAAAMB3AAHAAAAAAAAAD4////////BwAAAAAAAAAAAAAAAAAAAAAAAAAA4AfABwQAAAAAAAAAAAAeAAAAAAAAADAAAAAAAA8AAADwAACAA2AADwAAAAAAAAD4////////BwAAAAAAAAAAAAAAAAAAAAAAAAAAgA/wGQQAAAAAAAAAAAAOAAAAAAAAAAAAAAAA+AcAAADgAQCAAQDABwAAAAAAAADw////////AwDAAQAAAAAAAAAAAAAAAAAAAAAAAP55AAAAAAAAAAAAAAAOAAAAAAAAAAAAwPzh/gEAAADgAwCAAQDAAQAAAAAAAADw////////AQDAAQAAAAAAAAgAAAAAAAAAAAAAAPgfAAAAAAAAAAAAAAAcAAAAAAAAAAAA+P//DwAAAADIBwCAAfzkAAAAAAAAAADA////////AQAAAAAAAAAAAAgAAAAAAAAAAAAAADgPAAAAAAAAAAAAAAD4BwAAAAAAAADA/wf/AwAAAADeDwDgAf9/ABgAAAAAAADA////////AQAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAAAAAAADwDwAAAAAAAAD/PwQAAAAAAACAHQDggIc/AAAAAAAAAADA////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAABwAAAAAAAAHIAAAABgAPt/AAAAAAAAAACAOwDwzwEAAAAAAAAAAADA////////AAAAAAAAAOA/AAAAAAAAAAAAAAAAAAYAAAAAAABgAAAAOAABOIAAAAD88P8DAAAAAAAAAADAcQCw/wAAAAAAAAAAAAAA//////9/AAAAAIAAAP4fAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAA8AAAcAAAAAD//w8AAAAAAAAAAADg5ACwOQAAAAAAAAAAAAAA//////9/AAAAAMAAHz8YAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAwAwAYAAAgP/HDwAAAAAAAAAAAABgxgH4AAAAAAAAAAAAAADA//////8/AAAAAAAA/wcAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAA4M4AAA/P8DAAAAAAAAAAAAAAAAgMMfAAAAAAAAAAAAAAAA//////8fAADAAEcA9wEAAAAeAAAAAAAAAAAAAAMAAAAAAAAAAAAAwAYAwAAA/ncAAAAAAAAAAAAAAOAPAOcPAAAAAAAAAAAAAAAg//////8fAADg////DwAAAAAfAAAAAAAAAAAAAAcAAAAAAAAAAAAAgACAwACA/wBgAAAAAAAAAAAAAOAPAH4AAAAAAAAAAAAAAADA//////8PAAD8//3/BwAAAAAAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAgAHAPwBgAAAAAAAAAAAAAAAAADwAAAAAAAAAAAAAAACA//////8PAAD//wP45xAAAAAAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAAAABAPwBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACA//////8PAID//x/+//8AAAAAAAAAAAAAAAAwAAMAAAAAAAAAAAAAAAAABAb4AAAAAAAAAAAAAAAAAAAgAAwAAAAAAAAAAAAAAADA//////8PAMCDwv2fH/8BAAAAAAAAAAAAAAAQgAMAAAAAAAAAAAAAHgAAggz8AQAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAADA//////8HAPAAAPADAIADAAAAAAAAAAAAAAAIgAEAAAAAAAAAAAAADgAAwxz8AAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAACA//////8HAH4AAAAAAIAHAAAAAAAAAAAAAAAPgAEAAAAAAABgAAAAAAAAADg8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACA//////8H4K8BAAAAAAA+AAAAAAAAAAAAAMAPgAEAAAAAAAB4AAAAAAAAADA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+/////8H+YMBAAAAAMD8AwAAAAAAAAAAAIAAgAEAAAAAAAAIAAAAAAAAAHAcAAAAAAAAAAAAAAAAAIABAAAAAAAAAAAAAAAAAAAA8P//////fwAAAAAAAODgDwAAAAAAAAAAAAAAgAMAAAAAAAAAAAAAAAAAAOAPAAAAAAAAAAAAAAAAAIABAAAAAAAAAAAAAAAAAAAA+P//////HwAAAAAAAGAwPAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAMAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8P////8HAAAAAIAAAAAAeAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAPADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+P////8HAAAAAAAAAAAA4AEAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAAHABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4P////8HAAAAAAAAAAAAwwMAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAA4P////8HAAAAAAAAAAAAAH8AAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAA4P////8PAAAAAAAAAAIAAP4AAAAAAAAAAAAAgAMAAAAAAAAAAAAAAAAAAGAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE4P////8PAAAAAAAAAAAAAOAAAAAAAAAAAAAA3gEAAAAAAABAAAAAMAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM4P////8fAAAAAAAAAAAAAMADAAAAAAAAAAAAzgAAAAAAAADgAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAA8P////8fAAAAAAAAAAAAAIAHAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAADAAAAAAAAAAAADAAwAAAAAAAAA4AAAAAAAAAAAAAAAA+P////8/AAAAAAAAAAAAAAAOAAAAAAAAAAAwAAAAAAAAAAB4AAAAAAAAAPAAAAAAAAAAAADwAwAAAAAAAAAwAAAAAAAAAAAAAAAA/P////9/AAAAAAAAAAAAAAAcAAAAAAAAAAAwAAAAAAAAAADwAAAAAAAAAOAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAA+P////9/AAAAAAAAAAAAAAAcAAAAAAAAAAAQAAAAAAAAAADgAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+P//////AAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAACgAQAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+P//////AQAAAAAAAAAAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAA+P//////AQAAAAAAAAAAAABgAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAIABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAA+P//////AwAAAAAAAAAAAABgAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAIAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeAAAAAAAA8P//////BwAAAAAAAAAAAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+AAAAAAAA+P//////BwAAAAAAAAAAAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAA/P//////BwAAAAAAAAAAAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAA+P//////BwAAAAAAAAAAAADAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAA+P//////BwAAAAAAAAAAAACAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8P//////AwAAAAAAAAAAAQCAAwAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAGAAAABwAAAAAAAAMAAAAAAAAAAAAAAAAADAAAAAAA/P//////AQAAABgAAAAAAQAAAwAAAAAAAAAAAAAAAADADAAA+B8AAAAAAAAHAACABwAAAAAgAAAAAAAAAAAAAAAAAAAADAAAAAAA/v//////AQAAABAAAAAAAAAAAAAA+AAAAAAAAAAAAAAAAAAA8B8AAAAAAIADAAAABwAAAABgAAAAAAAAAAAAAAAAAAAADgAAAAAA/v//////AAAAAAAAAAAAAAAAAAAA8AMAAAAAAAAAAAAAAAAAwAMAAAAAAAAHAAAADgAAAABgAAAAAAAAAAAAAAAAAAAADAAAAAAA/v//////AAAAAAAAAAAAAAAAAAYAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAHgAAAAB4AAAAAAAAAAAAAAAAAAAAHAAAAACA////////AQAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAADgAAAABwAAAAAAAAAAAAAAAAAAAAOAAAAACA////////AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAADgAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAACA////////AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAACAAAAHgAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAA////////AwAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAABAAAAAAAGIAACAAAAACAAAAPgAAAABAAAAAAAQAAAAAAAAAAAAAcAAAAAAA////////AwAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAABAAAAAwAAAAAGB/AMAHAAAAAAAAAABAAAAAAAwAAAAAAAAIAAAA4AAAAAAA/P//////BwAAAAAAAAAAAAAAAAAAAAAAGEAAAAAAAAAAAAAgAAAAAAB+AMADAAAAAAAAAAAAAAAAAAwAAAAAAAAcAAAAwAAAAAAA+P//////BwAAAAAAAAAAAAAAAAAAAAAAHwAAAAAAAAAAAAAAAAAAAAAAAIABAAAAAAAAAAAAAAAAAAwAAAAAAAAPAAAAwAEAAAAA4P//////DwAAAAAAAAAAAAAAAAAAAAAAfwAAAAAAAAAAAAAAAAAAAAAAAIABAAAAAAAAAAAAAAEAAAAAAAAAAAAOAAAAgAMAAAAA4P//////DwAAAAAAAAAACAAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAMAAAAAwP//////DwAAAAAAAAAADgAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAMAAAAAwP//////DwAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAABAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMA4B8AgP//////DwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAEA8P8HgP//////BwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAgAGAP/APgP//////BwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAADAABAAAAAgAOADwAcAP//////BwAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAABwAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAfgAAA4AP//////BwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAABgAAADMAAAAAAAAAAAAAAAAAAHAAAAAAAAAP5/AAAwAP7/////AwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPw/AAAwAP7/////AwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAP7/////AwAAAAAAAAAAQAAHAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAADAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAADgAP//////AwAAAAAAAAAAYAAEAAAAAAAAAAAAAAAAAABwAAAAAAAAAAAAAAAABwAAQAAAADAAAAAAAAAAAAAEAAAAAwAAAAAAAADAAP//////AwAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAADgAAAAAAAAAAAAAAAABgAAQAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAACAg///////BwAAAAAAAAAAAAAAAAAAAAAAgAMAAAAAAADwAAAAAAAAAAAAAAAABwAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAA////////BwAAAAAAAAAAAAAAAAAAAAAA+AMAAAAAAABwAAAAAAAAAAAAAGwAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v//////BwAAAAAAAAAAAAAAAADgAQAA8AAAAAAAAAAwAAAAAAAAAAAAgP8BAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+P//////BwAAAAAAAAAAAAAAAADwAQAAIAAAAAAAAAAwAAAAAAAAAAAA8P8BBgAAgAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAA8P//////hwAAwP8HAAAAAAAAAAAAAAAAAAAAAAAgAAD8AQAAAMABgAAA/v/vDwAAwAcAAAAADAAAAAAAAAAAAAAA4P8AAAAAgBkA/P//////+wcA+P8fAAAAAAAAAAAAAAAAADAAAAD8AMD//wEAAPj//w8A/v//HwAA4N8PAAAAPCAAAMD/k4N+AAD8//8fAAAAwP8A/v/////////9//9/AAAAAAAAAAAAAADwATAAAAD/B/7///+wCfz//z/g////PwAA/P+fAwAA//0AAP7//9//APj///9/AAAA4P9/////////////////AQAAAACAAAAAAAD8MDDAB4D////////9j////////////wHA////lwMS//9/AP//////v///////AQDA////////////////////DwAAAADo7wAAAAD4/zn8//z/////////7////////////3///////5ff////////////////////HwD8////////////////////XwAAAAD+/z8AAAD8//////////////////////////////////////////////////////////////3/////////////////////fziAg/z//38AAGD////////////////////////////////////////////////////////////////////////////////////////f///////xA/z////////////////////////////////////////////////////////////////////////////////////////////////9D/7/////////////////////////////////////////////////////////////////////////////////////////////////v///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////";
const WATER_MASK = (() => {
  const bin = atob(WATER_MASK_B64);
  const a = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) a[i] = bin.charCodeAt(i);
  return a;
})();
// null — точка вне запечённой области (мир игры шире зафиксированного региона):
// там настоящих данных просто нет, и вызывающий откатывается на процедурную
// формулу, как было всегда.
function maskWaterAt(x, y) {
  const px = Math.floor((x + 0.5 + WATER_MASK_HALF_X) / WATER_MASK_STEP);
  const py = Math.floor((y + 0.5 + WATER_MASK_HALF_Z) / WATER_MASK_STEP);
  if (px < 0 || py < 0 || px >= WATER_MASK_W || py >= WATER_MASK_H) return null;
  const i = py * WATER_MASK_W + px;
  return ((WATER_MASK[i >> 3] >> (i & 7)) & 1) === 1;
}
function isRealWater(x, y) {
  const m = maskWaterAt(x, y);
  if (m !== null) return m;
  return rwHeightAt(x + 0.5, y + 0.5) < RW_SEA;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: CORS });
  try {
    const authHeader = req.headers.get("Authorization") || "";
    if (!authHeader) return jsonResponse({ err: "no auth" }, 401);

    const SUPABASE_URL = Deno.env.get("SUPABASE_URL");
    const ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY");
    const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");

    const callerClient = createClient(SUPABASE_URL, ANON_KEY, {
      global: { headers: { Authorization: authHeader } },
    });
    const { data: { user }, error: uErr } = await callerClient.auth.getUser();
    if (uErr || !user) return jsonResponse({ err: "bad token" }, 401);

    const body = await req.json().catch(() => ({}));
    const tx = Math.round(Number(body.x)), ty = Math.round(Number(body.y));
    if (!Number.isFinite(tx) || !Number.isFinite(ty)) return jsonResponse({ err: "нет координат" }, 400);

    const admin = createClient(SUPABASE_URL, SERVICE_KEY);
    const { data: world, error: wErr } = await admin
      .from("worlds").select("*").order("created_at", { ascending: true }).limit(1).maybeSingle();
    if (wErr) return jsonResponse({ err: wErr.message }, 500);
    if (!world) return jsonResponse({ err: "мира нет" }, 400);

    const { data: attRow, error: aErr } = await admin
      .from("players").select("*").eq("world_id", world.id).eq("auth_uid", user.id).maybeSingle();
    if (aErr) return jsonResponse({ err: aErr.message }, 500);
    if (!attRow) return jsonResponse({ err: "Игрок не найден — сначала mp-join" }, 400);

    if (tx === attRow.x && ty === attRow.y) return jsonResponse({ err: "Отряд и так дома" }, 400);
    if (isRealWater(tx, ty)) return jsonResponse({ err: "Здесь вода — отряд не высадить" }, 400);

    const attP = attRow.state;
    attP.race = attP.race || attRow.race;   // самоисцеление легаси-записей, как в mp-attack/mp-gather

    const hallLv = Array.isArray(attP.b.hall) ? Math.max(0, ...attP.b.hall) : attP.b.hall;
    // Слоты — общий пул со штурмом, рейдом и сбором; разведка считается
    // отдельно (см. index.html: в счётчике «Отряды в поле» её нет).
    const { data: outMarches, error: omErr } = await admin
      .from("marches").select("id,mode").eq("world_id", world.id).eq("player_id", attRow.id);
    if (omErr) return jsonResponse({ err: omErr.message }, 500);
    const busy = (outMarches || []).filter((m) => m.mode !== "scout" && m.mode !== "scoutmarch").length;
    if (busy >= marchSlots(hallLv)) return jsonResponse({ err: "Все отряды заняты" }, 400);

    const sendUnits = emptyUnits();
    let totalSend = 0;
    TKEYS.forEach((t) => {
      for (let i = 1; i <= 5; i++) {
        const want = Math.max(0, Math.round(Number((body.units && body.units[t] && body.units[t][i]) || 0)));
        const have = (attP.troops[t] && attP.troops[t][i]) || 0;
        const n = Math.min(want, have);
        sendUnits[t][i] = n; totalSend += n;
      }
    });
    if (totalSend <= 0) return jsonResponse({ err: "Отправьте хотя бы одного воина" }, 400);

    const B = bonuses(attP);
    const dist = Math.hypot(tx - attRow.x, ty - attRow.y);
    const spd = marchSpeed(sendUnits, attP.race, B.march);
    const travel = Math.max(MIN_TRAVEL, (dist / spd) * 60);

    // Полководец — тот же порядок, что и в mp-attack: он физически один и
    // берётся, только если не уехал с другим походом.
    const takeGen = !!body.with_gen && attP.gen && attP.gen.id != null && attP.gen.away == null;

    const nowSec = Date.now() / 1000;
    const { data: march, error: mErr } = await admin.from("marches").insert({
      world_id: world.id, player_id: attRow.id, mode: "move", state: "go",
      tx, ty, t0: nowSec, t1: nowSec + travel,
      // from — откуда отряд вышел: по нему клиент рисует линию похода, а
      // mp-redirect считает, где отряд сейчас. dist — расстояние ДО ДОМА, по
      // нему поедет обратная дорога, если отряд отзовут.
      units: sendUnits,
      data: { dist, spd, has_gen: takeGen, from: { x: attRow.x, y: attRow.y } },
    }).select().single();
    if (mErr) return jsonResponse({ err: mErr.message }, 500);

    TKEYS.forEach((t) => {
      for (let i = 1; i <= 5; i++) attP.troops[t][i] = Math.max(0, (attP.troops[t][i] || 0) - sendUnits[t][i]);
    });
    // Событие прибытия создаём ДО записи состояния игрока (см. тот же
    // разбор в mp-attack): тик мира событийный, обхода просроченных маршей
    // у него нет, и марш без своего события висел бы в пути вечно, держа
    // войска и слот отряда.
    const { data: evRow, error: evErr } = await admin.from("events").insert({
      world_id: world.id, fire_at: new Date((nowSec + travel) * 1000).toISOString(),
      type: "march_arrive", data: { march_id: march.id },
    }).select("id").single();
    if (evErr) {
      await admin.from("marches").delete().eq("id", march.id);
      return jsonResponse({ err: evErr.message }, 500);
    }
    const rollback = async () => {
      if (evRow) await admin.from("events").delete().eq("id", evRow.id);
      await admin.from("marches").delete().eq("id", march.id);
    };

    if (takeGen) attP.gen.away = march.id;
    const saved = await savePlayerState(admin, attRow, attP);
    // Проигранная гонка за строку игрока: отряд уже создан — убираем, иначе
    // повтор запроса (клиент повторяет молча, см. mpCall) отправит второй
    // такой же поход, а войска спишутся дважды. Тот же приём, что в mp-attack.
    if (saved.conflict) { await rollback(); return conflictResponse(); }
    if (saved.error) { await rollback(); return jsonResponse({ err: saved.error.message }, 500); }

    return jsonResponse({ ok: true, march_id: march.id, eta: travel, has_gen: takeGen });
  } catch (e) {
    return jsonResponse({ err: String(e && e.message || e) }, 500);
  }
});
